app:
  db:
    mysql:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        # place your database url
        url: 
        # place your database username
        username: 
        # place your database password
        password: 
        hikari:
          poolName: mySQLHikariConnectionPool
        xa:
          data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
      jpa:
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL57Dialect
            dialect.storage_engine: innodb
            transaction:
              jta:
                platform: com.example.distributedtransaction2.AtomikosJtaPlatform
          javax:
            persistence:
              transactionType: JTA
        hibernate:
          ddl-auto: create
    postgresql:
      datasource:
        driver-class-name: org.postgresql.Driver
        # place your database url
        url: 
        # place your database username
        username: 
        # place your database password
        password: 
        hikari:
          poolName: postgreSQLHikariConnectionPool
        xa:
          data-source-class-name: org.postgresql.xa.PGXADataSource
      jpa:
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL95Dialect
            jdbc:
              lob:
                non_contextual_creation: true
            transaction:
              jta:
                platform: com.example.distributedtransaction2.AtomikosJtaPlatform
          javax:
            persistence:
              transactionType: JTA
        hibernate:
          ddl-auto: create
